### ISSUE TITLE
`./build prereqs` requires a compiled build already?

### ISSUE THREAD

**Issue by zetashift** [geekrelief/gdnim#13]
I was setting up gdnim on a new user on my Ubuntu distro. And to `nim c build` I have to `nimble install` the `compiler` and `anycase` packages. Prereqs does this already but that's...kind of backwards haha?

Maybe do prereqs as a (Power)shell script for now and leverage Nimble/Nimph eventually(tm)?

**Comment by geekrelief** [comment]
I believe I pushed a fix for this already.  The build script is no longer dependent on `godotapi` which imports `compiler`.  I moved the api generation to a separate script in the `deps` folder.  There shouldn't be any noticeable difference for the end user.
