### ISSUE TITLE
Godot editor reports resource leaked if main_screen and/or custom_dock plugins enabled

### ISSUE THREAD

**Issue by derekdai** [geekrelief/gdnim#22]
I am not sure this should report to godot-nim or gdnim.

Godot editor reports resource leaked, if main_screen and/or custom_dock enabled. No matter building with arc/orc/realtime gc. 
```
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
   At: core/object.cpp:2132.
Leaked instance: ImageTexture:3216 - Resource path:
Leaked instance: SceneState:17848
Leaked instance: GDScript:17861 - Resource path: res://gdscripts/main_scene_button.gd
Leaked instance: PackedScene:17863 - Resource path: res://addons/main_screen/main_screen.tscn
Leaked instance: Image:3217 - Resource path:
Leaked instance: SceneState:17864
Leaked instance: GDScriptNativeClass:717
Leaked instance: PackedScene:17847 - Resource path: res://addons/custom_dock/custom_dock.tscn
Leaked instance: Button:17850 - Node name: Custom Dock
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:450.
Resource still in use: res://addons/custom_dock/custom_dock.tscn (PackedScene)
Resource still in use: res://addons/main_screen/main_screen.tscn (PackedScene)
Resource still in use: res://gdscripts/main_scene_button.gd (GDScript)
Orphan StringName: res://gdscripts/main_scene_button.gd
Orphan StringName: anchor_right
Orphan StringName: margin_bottom
Orphan StringName: __meta__
Orphan StringName: ImageTexture
Orphan StringName: CenterContainer
Orphan StringName: GDScriptNativeClass
Orphan StringName: size_flags_vertical
Orphan StringName: PackedScene
Orphan StringName: .
Orphan StringName: margin_left
Orphan StringName: Custom Dock
Orphan StringName: text
Orphan StringName: anchor_bottom
Orphan StringName: SceneState
Orphan StringName: Button
Orphan StringName: pressed
Orphan StringName: Image
Orphan StringName: margin_right
Orphan StringName: _on_PrintHello_pressed
Orphan StringName: _init
Orphan StringName: GDScript
Orphan StringName: margin_top
Orphan StringName: script
StringName: 24 unclaimed string names at exit.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:66.
```

**Comment by geekrelief** [comment]
Is this on exit? Like the other issue?

**Comment by derekdai** [comment]
Yes, the report is generated by godot. I run the editor directly without `./build gd` so I can add `--verbose` to see full report.

**Comment by geekrelief** [comment]
Hmm I wasn't even aware of the --verbose flag.  I just added it.  I see the leak, but on my system it only complains about custom_dock and only 2 StringNames but I don't see what I can do about it.  

```
WARNING: ObjectDB::cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core\object.cpp:2132
Leaked instance: Button:18338 - Node name: Custom Dock
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
Orphan StringName: Custom Dock
Orphan StringName: Button
StringName: 2 unclaimed string names at exit.
```

I'm already calling `queue_free`, and I'm niling the reference.  I wonder if there's an issue posted on the godotengine repo about this.

**Comment by geekrelief** [comment]
After more testing with Custom Dock, I think this is a godot engine issue.  If I enable and disable the dock, I get no error on exit, but if I enable the dock and exit the editor I get the leak warning.  So the editor isn't cleaning up things properly.
```nim
method exit_tree() =
    self.remove_control_from_docks(self.dock)
    self.dock.queue_free()
    self.dock = nil
```
I'm removing the dock and call `self.dock.queue_free()` which is what the warning is complaining about.  If I don't have the `remove_control_from_dock` call, then when you disable the dock, it stays there.  

I don't get any issues from the Main Screen plugin.  I'm going to have to look inside the engine to see what's going on.

**Comment by geekrelief** [comment]
Alright I'm going to put a big warning in the code and README.  I think GDNative needs a patch to fix this because the behavior is inconsistent.

**Comment by derekdai** [comment]
Agree.

**Comment by geekrelief** [comment]
I'm closing this issue, and the next push will contain comments on the tool scripts, README, and tasks.nim has been updated so when you use `./build gentool` the script will have a warning in it about the crashy / leaky behavior of GDNative tool scripts.
