### ISSUE TITLE
question？

### ISSUE THREAD

**Issue by txj-mssl** [geekrelief/gdnim#28]
Can this be used to develop a hot update for a game? Check whether the server has the latest version at the beginning of the game. If so, download the latest content and restart the game. Start the program again to see the new content.

**Comment by geekrelief** [comment]
I believe you can already do that with asset packs, but I haven't tried.  Hot reloading is the GDNative version of GDScript's `Sync Script Changes`.  But there's nothing preventing you from using the same technique for a hot update.

**Comment by txj-mssl** [comment]
I can't do it，Hope to provide demo

**Comment by geekrelief** [comment]
https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_pcks.html This is out of the scope of what gdnim does.

**Comment by txj-mssl** [comment]
know
