### ISSUE TITLE
Error: type expected, but got symbol 'Object' of kind 'enumField' 

### ISSUE THREAD

**Issue by DartCrusaderBn** [geekrelief/gdnim#33]
OS: Windows 10
Compiler: gcc
nim 2.0.0

error when building project with `build cleanbuild`
![image](https://github.com/geekrelief/gdnim/assets/64196105/4f7c6b51-83e8-4cad-84d9-c457555ccf3a)

**Comment by geekrelief** [comment]
Wtf, this is really weird. Not sure why it's rearing it's ugly head again. {.pure.} just doesn't work anymore. I'll need to make a bunch of edits to get it working again.

**Comment by geekrelief** [comment]
Fixed this with the latest PR.
